# Generated by Django 3.0.3 on 2020-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_main_abouttxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='seo_keywords',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_txt',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
