# Generated by Django 3.0.3 on 2020-04-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200413_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='utxt',
            field=models.TextField(),
        ),
    ]
