# Generated by Django 3.0.3 on 2020-04-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200413_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='ip',
            field=models.TextField(default=''),
        ),
    ]
